import Head from "next/head";
import { MasonryGrid } from "../components";

const srcs = [
  {
    type: "image",
    src: "https://i.ibb.co/N9d2TYc/CSS-Box-Sizing-Property.png",
  },
];

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen w-screen overflow-x-hidden bg-black p-4 text-white">
        <MasonryGrid srcs={srcs} />
      </div>
    </div>
  );
}
