import Head from "next/head";
import { MasonryGrid } from "../components";
import { useEffect, useState } from "react";
import supabase from "@/config/supabaseClient";


export default function Home() {
  const [visuals, setVisuals] = useState<any[]>([]);

  const fetchVisuals = async () => {
      const { data, error } = await supabase.from("visuals").select();

      error && console.error(error)
      data && setVisuals(data as any);
    };

    useEffect(() => {
      fetchVisuals();
    }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen w-screen overflow-x-hidden p-4 text-white">
        <MasonryGrid visuals={visuals} />
      </div>
    </div>
  );
}
